### PR TITLE
add ci / release action & update components

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <andre.bauer@staffbase.com>

To have easier docker image updates i've added some automation. 

Motivation was adding conntrack-stats-exporter helm chart to:
https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-conntrack-stats-exporter

* added github action
  * docker build on pr
    * https://github.com/docker/build-push-action is used to build amd64 and arm64 images
  * release amd64 and arm64 docker image to dockerhub 
    * when push to master the following docker images are released
      * conntrack-stats-exporter:sha-c2154ec
      * conntrack-stats-exporter:latest 
    * when a git tag (for example v0.2.4) is pushed the following docker images are released
      * conntrack-stats-exporter:v0.2.4
      * conntrack-stats-exporter:v0.2
      * conntrack-stats-exporter:v0
      * conntrack-stats-exporter:sha-c2154ec
      * conntrack-stats-exporter:latest
    * https://github.com/docker/metadata-action is used for tagging
    * examples of tags (outcome of current build with tag push)
      * https://hub.docker.com/repository/docker/monotek/conntrack-stats-exporter/tags
  * github secrets DOCKERHUB_USERNAME & DOCKERHUB_TOKEN needs to be set before merge
    * https://github.com/docker/login-action is used for docker login
* updates  
  * updated go to 1.18
  * updated go modules
  * updated docker image to use newest alpine image
* some markdown fixes
* some changes to build.sh to make automated multiarch build work

### CODE REVIEW

**Comment by monotek** [comment]
@jwkohnen
anything missing to get this merged?

**Comment by jwkohnen** [comment]
Hey! Thanks for your work, I really appreciate it. I was never a github action user so far and don't know much about it yet. I was not sure if you're done, since you kept pushing force pushes. 

How can we confirm everything works as intended before I merge?

**Comment by monotek** [comment]
Hi Johannes,

basically i've tested it in my github fork https://github.com/monotek/conntrack-stats-exporter which pushes to my own dockerhub repo: https://hub.docker.com/r/monotek/conntrack-stats-exporter/tags

So in my dockerhub repo already the newest build is available, which you could test if you want.

Only thing which needs to be done before the merge is to set the github repo secrets DOCKERHUB_USERNAME & DOCKERHUB_TOKEN in: https://github.com/jwkohnen/conntrack-stats-exporter/settings/secrets/actions

You might need to create a new dochkerhub token in https://hub.docker.com/settings/security, if you don't already have one.

Kind Regards
André

**Comment by jwkohnen** [comment]
For some reason I can't get a GitHub hosted runner configured, and I can't figure out why. My Google-fu is failing me. The config pages nag me towards configuring a self-hosted runner, but that seems wrong. Any clues?

**Comment by monotek** [comment]
Why do you want a self hosted runner?
Normally Github just takes care of it and provides a free one.

**Comment by jwkohnen** [comment]
I didn't say I wanted a self-hosted runner and I think it would be wrong thing to do for an artifact for public consumption. 

I agree that GitHub usually just takes care of it, yet it doesn't in this case. This is the mystery. I am a bit short in available time to debug this. Unless there is other input I'll have to put this on hold for about two weeks.

**Comment by monotek** [comment]
Sorry, I misunderstood.

All this stuff will only work after it's merged. 

I'm happy to help if there are any problems popping up afterwards.

**Comment by monotek** [comment]
Friendly ping :)

**Comment by monotek** [comment]
Any way we i can help to get that merged?
We'd like to use the updated version of the image.

**Comment by jwkohnen** [comment]
This PR has been merge into branch main; Branch master will be deleted at some point. Closing this as GitHub did not catch the merge.

**Comment by jwkohnen** [comment]
I'll let this stew for a couple days until Go 1.18.4 is released on Tuesday (a security release) before pushing a new tag.

**Comment by monotek** [comment]
👍

**Comment by jwkohnen** [comment]
done

Thank you for your contribution!

**Pull request closed without merging**
